"""Type stubs for the compiled extension module."""

from __future__ import annotations

import enum
from typing import List, Optional

import numpy as np
from numpy.typing import NDArray

__version__: str

class Rate(enum.Enum):
    IMBE_7200X4400 = ...
    IMBE_4400X4400 = ...
    AMBEPLUS2_3600X2450 = ...
    AMBEPLUS2_2450X2450 = ...

class Vocoder:
    rate: Rate
    frame_samples: int
    fec_frame_bytes: int

    def __init__(self, rate: Rate) -> None: ...
    def encode_pcm(self, pcm: NDArray[np.int16]) -> bytes: ...
    def decode_bits(self, bits: bytes) -> NDArray[np.int16]: ...
    def reset(self) -> None: ...

class LiveEncoder:
    rate: Rate
    pending_samples: int

    def __init__(self, rate: Rate) -> None: ...
    def push(self, pcm: NDArray[np.int16]) -> List[bytes]: ...
    def flush(self) -> Optional[bytes]: ...
    def discard_pending(self) -> None: ...
    def reset(self) -> None: ...

class LiveDecoder:
    rate: Rate
    pending_bytes: int

    def __init__(self, rate: Rate) -> None: ...
    def push(self, bits: bytes) -> List[NDArray[np.int16]]: ...
    def discard_pending(self) -> None: ...
    def reset(self) -> None: ...

class Transcoder:
    def __init__(self, src: Rate, dst: Rate) -> None: ...
    def transcode(self, bits: bytes) -> bytes: ...
    def reset(self) -> None: ...
