"""Type stubs for the compiled extension module."""

from __future__ import annotations

import enum
from typing import List, Optional, Tuple

import numpy as np
from numpy.typing import NDArray

__version__: str

class Rate(enum.Enum):
    IMBE_7200X4400 = ...
    IMBE_4400X4400 = ...
    AMBEPLUS2_3600X2450 = ...
    AMBEPLUS2_2450X2450 = ...

class AmbePlus2Synth(enum.Enum):
    AMBE_PLUS = ...
    BASELINE = ...

class EnhancementMode(enum.Enum):
    NONE = ...
    CLASSICAL = ...

class Vocoder:
    rate: Rate
    frame_samples: int
    fec_frame_bytes: int

    # Encoder knobs
    tone_detection: bool
    spectral_subtraction: bool
    silence_dispatch: bool
    chip_compat: bool
    chip_compat_spectral_clamp: bool
    pitch_silence_override: bool
    default_pitch_on_silence: bool
    pyin_pitch: bool
    amp_ema_alpha: float
    repeat_reset_after: Optional[int]
    ambe_plus2_synth: AmbePlus2Synth
    enhancement: EnhancementMode

    def __init__(self, rate: Rate) -> None: ...
    def encode_pcm(self, pcm: NDArray[np.int16]) -> bytes: ...
    def decode_bits(self, bits: bytes) -> NDArray[np.int16]: ...
    def reset(self) -> None: ...

    def set_tone_detection(self, on: bool) -> None: ...
    def set_spectral_subtraction(self, on: bool) -> None: ...
    def set_silence_dispatch(self, on: bool) -> None: ...
    def set_chip_compat(self, on: bool) -> None: ...
    def set_chip_compat_spectral_clamp(self, on: bool) -> None: ...
    def set_pitch_silence_override(self, on: bool) -> None: ...
    def set_default_pitch_on_silence(self, on: bool) -> None: ...
    def set_pyin_pitch(self, on: bool) -> None: ...
    def set_amp_ema_alpha(self, alpha: float) -> None: ...
    def set_repeat_reset_after(self, n: Optional[int] = None) -> None: ...
    def set_ambe_plus2_synth(self, gen: AmbePlus2Synth) -> None: ...
    def set_enhancement(self, mode: EnhancementMode) -> None: ...

    def last_output_kind(self) -> Optional[str]: ...
    def last_tone_detection(self) -> Optional[Tuple[int, int]]: ...

class LiveEncoder:
    rate: Rate
    pending_samples: int

    def __init__(self, rate: Rate) -> None: ...
    def push(self, pcm: NDArray[np.int16]) -> List[bytes]: ...
    def flush(self) -> Optional[bytes]: ...
    def discard_pending(self) -> None: ...
    def reset(self) -> None: ...

class LiveDecoder:
    rate: Rate
    pending_bytes: int

    def __init__(self, rate: Rate) -> None: ...
    def push(self, bits: bytes) -> List[NDArray[np.int16]]: ...
    def discard_pending(self) -> None: ...
    def reset(self) -> None: ...

class Transcoder:
    def __init__(self, src: Rate, dst: Rate) -> None: ...
    def transcode(self, bits: bytes) -> bytes: ...
    def reset(self) -> None: ...
