"""Type stubs for the rate33 half-rate channel-frame submodule."""

from __future__ import annotations

from typing import List, Sequence

import numpy as np
from numpy.typing import NDArray

INFO_WIDTHS: List[int]
CODE_WIDTHS: List[int]
INFO_BITS_TOTAL: int
R34_BIT_ORDER: List[int]
PN_SEQ_LEN: int
DIBITS_PER_FRAME: int
SOFT_BITS: int
AMBE_B_COUNT: int
AMBE_PARAM_WIDTHS: List[int]
AMBE_VECTOR_WIDTHS: List[int]

class Rate33Frame:
    info: List[int]
    errors: List[int]

    def error_total(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

# no-FEC byte orders
def pack_no_fec(info: Sequence[int]) -> bytes: ...
def unpack_no_fec(frame: bytes) -> List[int]: ...
def natural_to_info(frame: bytes) -> List[int]: ...
def info_to_natural(info: Sequence[int]) -> bytes: ...

# FEC core
def deinterleave(dibits: Sequence[int]) -> List[int]: ...
def interleave(codewords: Sequence[int]) -> List[int]: ...
def pn_sequence(u0: int) -> List[int]: ...
def modulation_masks(u0: int) -> List[int]: ...
def demodulate(codewords: Sequence[int], u0: int) -> List[int]: ...
def decode_code_vectors(codewords: Sequence[int]) -> Rate33Frame: ...
def decode_frame(dibits: Sequence[int]) -> Rate33Frame: ...
def decode_frame_soft(soft: NDArray[np.int8]) -> Rate33Frame: ...
def encode_frame(info: Sequence[int]) -> List[int]: ...

# priority
def prioritize(b: Sequence[int]) -> List[int]: ...
def deprioritize(u: Sequence[int]) -> List[int]: ...

# byte <-> dibit
def unpack_dibits(data: bytes) -> List[int]: ...
def pack_dibits(dibits: Sequence[int]) -> bytes: ...

# field-dump conveniences
def fields_from_fec(frame: bytes) -> List[int]: ...
def fields_from_no_fec(frame: bytes) -> List[int]: ...
def fields_from_natural(frame: bytes) -> List[int]: ...
